name: mushafapp
description: "Quran Mushaf app with QPC v4 Tajweed fonts."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.3
  sqflite_common_ffi: ^2.3.4
  path_provider: ^2.1.4
  path: ^1.9.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/v4/
    - assets/data/

  fonts:
    - family: QCF4Surah
      fonts:
        - asset: assets/fonts/QCF4_QBSML.ttf
    - family: UthmanicHafs
      fonts:
        - asset: assets/fonts/uthmanic_hafs_v20.ttf
